#!/bin/bash
SERVERS="192.168.9.207 192.168.9.208"
PASSWD="123qwe!@#QWE"

function sshcopyid
{
    expect -c "
        set timeout -1;
        spawn ssh-copy-id $1;
        expect {
            \"yes/no\" { send \"yes\r\" ;exp_continue; }
            \"password:\" { send \"$PASSWD\r\";exp_continue; }
        };
        expect eof;
    "
}

function p_while {
   grep -Ev "#|^$" $file | while read server
   do
     sshcopyid $server
   done
}

function p_for {
  for server in $SERVERS
  do
      sshcopyid $server
  done
}
